spring:
  application:
    name: jwt-demo
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem