spring:
  application:
    name: jwt-demo
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
#      Here Hibernate will create the DB Table just by reading the entity classes
      ddl-auto: create
  sql:
    init:
#      Here we stopped Spring to initialize the database using the script files 'data.sql' and 'schema.sql'
      mode: never

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem